name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Android SDK
        run: sudo apt-get install -y openjdk-11-jdk android-sdk

      - name: Build with Gradle
        run: ./gradlew assembleDebug
